### ISSUE TITLE
Question: Integration with api docs

### ISSUE THREAD

**Issue by tomsarduy** [ndelvalle/generator-api#30]
This is more an enhancement and a question, but it would be nice to have at least optional, support or integration with API docs: http://apidocjs.com, since this is a restful API design, make sense to have some kind of API documentation

**Comment by ndelvalle** [comment]
Hi @tomsarduy sorry for the slow replay. I'm not sure about this feature, because even if users wants it, just a couple of them would want to use apidocsjs, maybe some would like to implement another one. I know is useful to have it, but is not a priority for me. Implementing tests is in my TODO list for now 🙂. Anyways if you or somebody else wants to implement it, its totally cool with me.
